// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"application/domain"
	"application/pkg/todo"
	"github.com/uptrace/bun"
)

// Injectors from wire.go:

func Initialize(db *bun.DB) *domain.Services {
	todoRepository := todo.NewRepository(db)
	todoService := todo.NewService(todoRepository)
	services := &domain.Services{
		TodoService: todoService,
	}
	return services
}
